/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Visao;

import Controle.PagamentoEscolar;
import Controle.PagamentoTurismo;
import static Validacoes.ValidaData.calculaData;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lailson-pc
 */
public class ConsultarPagamentos extends javax.swing.JFrame {

    ArrayList listaEscolar = new ArrayList();
    ArrayList listaTurismo = new ArrayList();
    
    /**
     * Creates new form ConsultarPagamentos
     */
    public ConsultarPagamentos() {
        initComponents();
        atualiza();
    }
    
    private Object getSelectedObject() {
         Object selecionado = null;
         int linhaSelecionada = tabelaTurismo.getSelectedRow();
         if(linhaSelecionada >= 0){
             selecionado = listaTurismo.get(linhaSelecionada);
         }else{
             JOptionPane.showMessageDialog(this, "Selecione um elemento da tabela.");
         }
         return selecionado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEscolar = new javax.swing.JTable();
        buscaEscolar = new javax.swing.JButton();
        dataEscolar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        atTabEsc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaTurismo = new javax.swing.JTable();
        add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dataTurismo = new javax.swing.JTextField();
        buscaTurismo = new javax.swing.JButton();
        atTabTur = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        fechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(115, 117, 118), 3, true));

        jLabel24.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel24.setText("Consultar Pagamentos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Escolar"));

        tabelaEscolar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaEscolar);

        buscaEscolar.setText("Buscar Escolar");
        buscaEscolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaEscolarActionPerformed(evt);
            }
        });

        jLabel3.setText("Busca por Mes e Ano:");

        atTabEsc.setText("Atualiza Tabela");
        atTabEsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atTabEscActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel2.setText("(mm/aaaa)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscaEscolar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(atTabEsc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dataEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscaEscolar)
                    .addComponent(atTabEsc)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Turismo"));

        tabelaTurismo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelaTurismo);

        add.setText("Adicionar Pagamento Parcela");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel1.setText("Busca por Mes e Ano:");

        buscaTurismo.setText("Buscar Turismo");
        buscaTurismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaTurismoActionPerformed(evt);
            }
        });

        atTabTur.setText("Atualiza Tabela");
        atTabTur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atTabTurActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel4.setText("(mm/aaaa)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(add)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataTurismo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscaTurismo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(atTabTur, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dataTurismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscaTurismo)
                    .addComponent(atTabTur)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(add))
        );

        fechar.setText("Fechar");
        fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharjButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel24)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(fechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecharjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharjButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_fecharjButton2ActionPerformed

    private void buscaEscolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaEscolarActionPerformed
        // TODO add your handling code here:
        if(dataEscolar.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe uma data para busca.");
            return;
        }
        String data = dataEscolar.getText();
        data = "01/" + data;
        if(calculaData(data) == false){
            JOptionPane.showMessageDialog(null, "Data incorreta.\nDigite uma data do Tipo 'mm/aaaa'.");
            return;
        }
        atualizaTabelaEscolar(data);
    }//GEN-LAST:event_buscaEscolarActionPerformed

    private void atTabEscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atTabEscActionPerformed
        // TODO add your handling code here:
        atualizaTabelaEscolar("");
    }//GEN-LAST:event_atTabEscActionPerformed

    private void atTabTurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atTabTurActionPerformed
        // TODO add your handling code here:
        atualizaTabelaTurismo("");
    }//GEN-LAST:event_atTabTurActionPerformed

    private void buscaTurismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaTurismoActionPerformed
        // TODO add your handling code here:
        if(dataTurismo.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe uma data para busca.");
            return;
        }
        if(dataTurismo.getText().length() != 7){
            JOptionPane.showMessageDialog(null, "Data incorreta.\nDigite uma data do Tipo 'mm/aaaa'.");
            return;
        }
        String data = dataTurismo.getText();
        data = "01/" + data;
        if(calculaData(data) == false){
            JOptionPane.showMessageDialog(null, "Data incorreta.\nDigite uma data do Tipo 'mm/aaaa'.");
            return;
        }
        atualizaTabelaTurismo(data);
    }//GEN-LAST:event_buscaTurismoActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        Object o = getSelectedObject();
        PagamentoTurismo p = (PagamentoTurismo)o;
        
        if (o != null){
            if(p.getParcelas() != p.getParcelasPaga()){
                new PagarParcela(p).setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Todas as parcelas ja foram pagas.");
            }
        }
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarPagamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton atTabEsc;
    private javax.swing.JButton atTabTur;
    private javax.swing.JButton buscaEscolar;
    private javax.swing.JButton buscaTurismo;
    private javax.swing.JTextField dataEscolar;
    private javax.swing.JTextField dataTurismo;
    private javax.swing.JButton fechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable tabelaEscolar;
    private javax.swing.JTable tabelaTurismo;
    // End of variables declaration//GEN-END:variables

    public void atualiza(){
        atualizaTabelaEscolar("");
        atualizaTabelaTurismo("");
    }
    
    private void atualizaTabelaEscolar(String data) {
        try{
            String mensagem;
            String[] nomesColunas = {"Código", "Nome", "CPF", "Valor", "Data"};
            if (data.length() > 0){
                String mesAno = data.substring(3, 10);
                listaEscolar = new ArrayList(PagamentoEscolar.consultarPagamentoData(mesAno));
                mensagem = "Não existem Pagamentos de Escolar na data " + mesAno + ".";
            }else{
                listaEscolar = new ArrayList(PagamentoEscolar.consultarPagamento());
                mensagem = "Não existem Pagamentos de Escolares efetuado.";
                dataEscolar.setText("");
            }
            Object[][] dadosVetor = new Object[listaEscolar.size()][nomesColunas.length];
            for (int i=0; i<listaEscolar.size(); i++){
                PagamentoEscolar pag = (PagamentoEscolar)listaEscolar.get(i);
                dadosVetor[i][0] = pag.getId();
                dadosVetor[i][1] = pag.getNome();
                dadosVetor[i][2] = pag.getCpf();
                dadosVetor[i][3] = pag.getValor();
                dadosVetor[i][4] = pag.getData();
            }
            DefaultTableModel modelo = new DefaultTableModel(dadosVetor,nomesColunas);
            tabelaEscolar.setModel(modelo);
            if(listaEscolar.isEmpty()){
                JOptionPane.showMessageDialog(this, mensagem);
            }
        }catch(StringIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this, "Data incorreta.\nDigite uma data do Tipo 'mm/aaaa'.");
        }
    }
    
    private void atualizaTabelaTurismo(String data) {
        try{
            String mensagem;
            String[] nomesColunas = {"Código", "Nome", "CPF", "id Viagem", "Valor", "Parcelas", "Parcelas Pagas", "Data"};
            if (data.length() > 0){ //&& data.length() == 10
                String mesAno = data.substring(3, 10);
                listaTurismo = new ArrayList(PagamentoTurismo.consultarPagamentoData(mesAno));
                mensagem = "Não existem Pagamentos de Turismo na data " + mesAno + ".";
            }else{
                listaTurismo = new ArrayList(PagamentoTurismo.consultarPagamento());
                mensagem = "Não existem Pagamentos de Turismo efetuados.";
                dataTurismo.setText("");
            }
            Object[][] dadosVetor = new Object[listaEscolar.size()][nomesColunas.length];
            for (int i=0; i<listaTurismo.size(); i++){
                PagamentoTurismo pag = (PagamentoTurismo)listaTurismo.get(i);
                dadosVetor[i][0] = pag.getId();
                dadosVetor[i][1] = pag.getNome();
                dadosVetor[i][2] = pag.getCpf();
                dadosVetor[i][3] = pag.getIdViagem();
                dadosVetor[i][4] = pag.getValor();
                dadosVetor[i][5] = pag.getParcelas();
                dadosVetor[i][6] = pag.getParcelasPaga();
                dadosVetor[i][7] = pag.getData();
            }
            DefaultTableModel modelo = new DefaultTableModel(dadosVetor,nomesColunas);
            tabelaTurismo.setModel(modelo);
            if(listaTurismo.isEmpty()){
                JOptionPane.showMessageDialog(this, mensagem);
            }
        }catch(StringIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this, "Data incorreta.\nDigite uma data do Tipo 'mm/aaaa'.");
        }
    }
}
