/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Visao;

/**
 *
 * @author guitonsic
 */
public class Sistema extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Sistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        empresa = new javax.swing.JMenu();
        alterarDados = new javax.swing.JMenuItem();
        consultarDados = new javax.swing.JMenuItem();
        CadLogin = new javax.swing.JMenuItem();
        cadastro = new javax.swing.JMenu();
        clienteMenu = new javax.swing.JMenuItem();
        escolaresMenu = new javax.swing.JMenuItem();
        funcionariosMenu = new javax.swing.JMenuItem();
        motoristasMenu = new javax.swing.JMenuItem();
        veiculosMenu = new javax.swing.JMenuItem();
        pecasMenu = new javax.swing.JMenuItem();
        servico = new javax.swing.JMenu();
        escolarServico = new javax.swing.JMenuItem();
        viagensServico = new javax.swing.JMenuItem();
        financeiro = new javax.swing.JMenu();
        atualizarFinanceiro = new javax.swing.JMenuItem();
        consultarFinanceiro = new javax.swing.JMenuItem();
        relatorioFinanceiro = new javax.swing.JMenuItem();
        novoRelatorioFinanceiro = new javax.swing.JMenuItem();
        pagamentoFinanceiro = new javax.swing.JMenuItem();
        consultas = new javax.swing.JMenu();
        clientesConsultas = new javax.swing.JMenuItem();
        turista = new javax.swing.JMenuItem();
        funcionariosConsultas = new javax.swing.JMenuItem();
        motorista = new javax.swing.JMenuItem();
        pecas = new javax.swing.JMenuItem();
        veiculosConsultas = new javax.swing.JMenuItem();
        transporteConsultas = new javax.swing.JMenuItem();
        viagensConsultas = new javax.swing.JMenuItem();
        InfoMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(115, 117, 118), 3, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(116, 117, 125));
        jMenuBar1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N

        empresa.setText("Empresa");
        empresa.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaActionPerformed(evt);
            }
        });

        alterarDados.setText("Alterar Dados");
        alterarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarDadosActionPerformed(evt);
            }
        });
        empresa.add(alterarDados);

        consultarDados.setText("Consultar Dados");
        consultarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarDadosActionPerformed(evt);
            }
        });
        empresa.add(consultarDados);

        CadLogin.setText("Cadastrar Login");
        CadLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadLoginActionPerformed(evt);
            }
        });
        empresa.add(CadLogin);

        jMenuBar1.add(empresa);

        cadastro.setText("Cadastros");
        cadastro.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N

        clienteMenu.setText("Clientes de Turismo");
        clienteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteMenuActionPerformed(evt);
            }
        });
        cadastro.add(clienteMenu);

        escolaresMenu.setText("Clientes Escolares");
        escolaresMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolaresMenuActionPerformed(evt);
            }
        });
        cadastro.add(escolaresMenu);

        funcionariosMenu.setText("Funcionários");
        funcionariosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionariosMenuActionPerformed(evt);
            }
        });
        cadastro.add(funcionariosMenu);

        motoristasMenu.setText("Motoristas");
        motoristasMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motoristasMenuActionPerformed(evt);
            }
        });
        cadastro.add(motoristasMenu);

        veiculosMenu.setText("Veículos");
        veiculosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculosMenuActionPerformed(evt);
            }
        });
        cadastro.add(veiculosMenu);

        pecasMenu.setText("Peças");
        pecasMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pecasMenuActionPerformed(evt);
            }
        });
        cadastro.add(pecasMenu);

        jMenuBar1.add(cadastro);

        servico.setText("Serviços");
        servico.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N

        escolarServico.setText("Trans. Escolar");
        escolarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolarServicoActionPerformed(evt);
            }
        });
        servico.add(escolarServico);

        viagensServico.setText("Viagens");
        viagensServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viagensServicoActionPerformed(evt);
            }
        });
        servico.add(viagensServico);

        jMenuBar1.add(servico);

        financeiro.setText("Financeiro");
        financeiro.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N

        atualizarFinanceiro.setText("Atualizar");
        atualizarFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarFinanceiroActionPerformed(evt);
            }
        });
        financeiro.add(atualizarFinanceiro);

        consultarFinanceiro.setText("Consultar");
        consultarFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarFinanceiroActionPerformed(evt);
            }
        });
        financeiro.add(consultarFinanceiro);

        relatorioFinanceiro.setText("Consultar Relatórios");
        relatorioFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioFinanceiroActionPerformed(evt);
            }
        });
        financeiro.add(relatorioFinanceiro);

        novoRelatorioFinanceiro.setText("Novo Relatório");
        novoRelatorioFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoRelatorioFinanceiroActionPerformed(evt);
            }
        });
        financeiro.add(novoRelatorioFinanceiro);

        pagamentoFinanceiro.setText("Pagamento");
        pagamentoFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagamentoFinanceiroActionPerformed(evt);
            }
        });
        financeiro.add(pagamentoFinanceiro);

        jMenuBar1.add(financeiro);

        consultas.setText("Consultas");
        consultas.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        consultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultasActionPerformed(evt);
            }
        });

        clientesConsultas.setText("Clientes Escolares");
        clientesConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesConsultasActionPerformed(evt);
            }
        });
        consultas.add(clientesConsultas);

        turista.setText("Clientes Turismo");
        turista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turistaActionPerformed(evt);
            }
        });
        consultas.add(turista);

        funcionariosConsultas.setText("Funcionários");
        funcionariosConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionariosConsultasActionPerformed(evt);
            }
        });
        consultas.add(funcionariosConsultas);

        motorista.setText("Motoristas");
        motorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motoristaActionPerformed(evt);
            }
        });
        consultas.add(motorista);

        pecas.setText("Peças");
        pecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pecasActionPerformed(evt);
            }
        });
        consultas.add(pecas);

        veiculosConsultas.setText("Veículos");
        veiculosConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculosConsultasActionPerformed(evt);
            }
        });
        consultas.add(veiculosConsultas);

        transporteConsultas.setText("Trans. Escolar");
        transporteConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transporteConsultasActionPerformed(evt);
            }
        });
        consultas.add(transporteConsultas);

        viagensConsultas.setText("Viagens");
        viagensConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viagensConsultasActionPerformed(evt);
            }
        });
        consultas.add(viagensConsultas);

        jMenuBar1.add(consultas);

        InfoMenu.setText("Info");
        InfoMenu.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jMenuBar1.add(InfoMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void alterarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarDadosActionPerformed
        // TODO add your handling code here:
        AlterarEmpresa alt = new AlterarEmpresa();
        alt.setLocationRelativeTo(null);
        alt.setVisible(true);
        //dispose();
    }//GEN-LAST:event_alterarDadosActionPerformed

    private void consultarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarDadosActionPerformed
        // TODO add your handling code here:
        ConsultarEmpresa emp = new ConsultarEmpresa();
        emp.setLocationRelativeTo(null);
        emp.setVisible(true);
        //dispose();
    }//GEN-LAST:event_consultarDadosActionPerformed

    private void empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_empresaActionPerformed
    
    private void clienteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteMenuActionPerformed
        // TODO add your handling code here:
        CadastrarCliente cad1 = new CadastrarCliente();
        cad1.setLocationRelativeTo(null);
        cad1.setVisible(true);
        //dispose();
    }//GEN-LAST:event_clienteMenuActionPerformed

    private void escolaresMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolaresMenuActionPerformed
        // TODO add your handling code here:
        CadastrarEscolar cad1 = new CadastrarEscolar();
        cad1.setLocationRelativeTo(null);
        cad1.setVisible(true);
        //dispose();
    }//GEN-LAST:event_escolaresMenuActionPerformed

    private void funcionariosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionariosMenuActionPerformed
        // TODO add your handling code here:
        CadastrarFuncionario cad1 = new CadastrarFuncionario();
        cad1.setLocationRelativeTo(null);
        cad1.setVisible(true);
        //dispose();
    }//GEN-LAST:event_funcionariosMenuActionPerformed

    private void motoristasMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motoristasMenuActionPerformed
        // TODO add your handling code here:
        CadastrarMotorista cad1 = new CadastrarMotorista();
        cad1.setLocationRelativeTo(null);
        cad1.setVisible(true);
        //dispose();
    }//GEN-LAST:event_motoristasMenuActionPerformed

    private void veiculosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculosMenuActionPerformed
        // TODO add your handling code here:
        CadastrarVeiculo cad1 = new CadastrarVeiculo();
        cad1.setLocationRelativeTo(null);
        cad1.setVisible(true);
        //dispose();
    }//GEN-LAST:event_veiculosMenuActionPerformed

    private void escolarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolarServicoActionPerformed
        // TODO add your handling code here:
        ServicoEscolar cad1 = new ServicoEscolar();
        cad1.setLocationRelativeTo(null);
        cad1.setVisible(true);
        //dispose();
    }//GEN-LAST:event_escolarServicoActionPerformed

    private void viagensServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viagensServicoActionPerformed
        // TODO add your handling code here:
        ServicoViagem cad1 = new ServicoViagem();
        cad1.setLocationRelativeTo(null);
        cad1.setVisible(true);
        //dispose();
    }//GEN-LAST:event_viagensServicoActionPerformed

    private void atualizarFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarFinanceiroActionPerformed
        // TODO add your handling code here:
        AtualizarFinan cad1 = new AtualizarFinan();
        cad1.setLocationRelativeTo(null);
        cad1.setVisible(true);
        //dispose();
    }//GEN-LAST:event_atualizarFinanceiroActionPerformed

    private void consultarFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarFinanceiroActionPerformed
        // TODO add your handling code here:
        ConsultarFinan cad1 = new ConsultarFinan();
        cad1.setLocationRelativeTo(null);
        cad1.setVisible(true);
        //dispose();
    }//GEN-LAST:event_consultarFinanceiroActionPerformed

    private void relatorioFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioFinanceiroActionPerformed
        // TODO add your handling code here:
        ConsultarRelatorio cad1 = new ConsultarRelatorio();
        cad1.setLocationRelativeTo(null);
        cad1.setVisible(true);
        //dispose();
    }//GEN-LAST:event_relatorioFinanceiroActionPerformed

    private void novoRelatorioFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoRelatorioFinanceiroActionPerformed
        // TODO add your handling code here:
        NovoRelatorio cad1 = new NovoRelatorio();
        cad1.setLocationRelativeTo(null);
        cad1.setVisible(true);
        //dispose();
    }//GEN-LAST:event_novoRelatorioFinanceiroActionPerformed

    private void pagamentoFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagamentoFinanceiroActionPerformed
        // TODO add your handling code here:
        Pagamento pag = new Pagamento();
        pag.setLocationRelativeTo(null);
        pag.setVisible(true);
        //dispose();
    }//GEN-LAST:event_pagamentoFinanceiroActionPerformed

    private void clientesConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesConsultasActionPerformed
        // TODO add your handling code here:
        ConsEscolar esc = new ConsEscolar();
        esc.setLocationRelativeTo(null);
        esc.setVisible(true);
        //dispose();
    }//GEN-LAST:event_clientesConsultasActionPerformed

    private void funcionariosConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionariosConsultasActionPerformed
        // TODO add your handling code here:
        ConsFuncionario cad1 = new ConsFuncionario();
        cad1.setLocationRelativeTo(null);
        cad1.setVisible(true);
        //dispose();
    }//GEN-LAST:event_funcionariosConsultasActionPerformed

    private void veiculosConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculosConsultasActionPerformed
        // TODO add your handling code here:
        ConsVeiculo cad1 = new ConsVeiculo();
        cad1.setLocationRelativeTo(null);
        cad1.setVisible(true);
        //dispose();
    }//GEN-LAST:event_veiculosConsultasActionPerformed

    private void transporteConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transporteConsultasActionPerformed
        // TODO add your handling code here:
        ConsTransEscolar cad1 = new ConsTransEscolar();
        cad1.setLocationRelativeTo(null);
        cad1.setVisible(true);
        //dispose();
    }//GEN-LAST:event_transporteConsultasActionPerformed

    private void viagensConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viagensConsultasActionPerformed
        // TODO add your handling code here:
        ConsViagem cad1 = new ConsViagem();
        cad1.setLocationRelativeTo(null);
        cad1.setVisible(true);
        //dispose();
    }//GEN-LAST:event_viagensConsultasActionPerformed

    private void pecasMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pecasMenuActionPerformed
        // TODO add your handling code here:
        CadastrarPecas peca = new CadastrarPecas();
        peca.setLocationRelativeTo(null);
        peca.setVisible(true);
    }//GEN-LAST:event_pecasMenuActionPerformed

    private void CadLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadLoginActionPerformed
        // TODO add your handling code here:
        CadastrarLogin log = new CadastrarLogin();
        log.setLocationRelativeTo(null);
        log.setVisible(true);        
    }//GEN-LAST:event_CadLoginActionPerformed

    private void consultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultasActionPerformed

    private void pecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pecasActionPerformed
        // TODO add your handling code here:
        ConsPecas peca = new ConsPecas();
        peca.setLocationRelativeTo(null);
        peca.setVisible(true);
    }//GEN-LAST:event_pecasActionPerformed

    private void motoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motoristaActionPerformed
        // TODO add your handling code here:
        ConsMotorista mot = new ConsMotorista();
        mot.setLocationRelativeTo(null);
        mot.setVisible(true);
    }//GEN-LAST:event_motoristaActionPerformed

    private void turistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turistaActionPerformed
        // TODO add your handling code here:
        ConsTurista tur = new ConsTurista();
        tur.setLocationRelativeTo(null);
        tur.setVisible(true);
    }//GEN-LAST:event_turistaActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadLogin;
    private javax.swing.JMenu InfoMenu;
    private javax.swing.JMenuItem alterarDados;
    private javax.swing.JMenuItem atualizarFinanceiro;
    private javax.swing.JMenu cadastro;
    private javax.swing.JMenuItem clienteMenu;
    private javax.swing.JMenuItem clientesConsultas;
    private javax.swing.JMenuItem consultarDados;
    private javax.swing.JMenuItem consultarFinanceiro;
    private javax.swing.JMenu consultas;
    private javax.swing.JMenu empresa;
    private javax.swing.JMenuItem escolarServico;
    private javax.swing.JMenuItem escolaresMenu;
    private javax.swing.JMenu financeiro;
    private javax.swing.JMenuItem funcionariosConsultas;
    private javax.swing.JMenuItem funcionariosMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem motorista;
    private javax.swing.JMenuItem motoristasMenu;
    private javax.swing.JMenuItem novoRelatorioFinanceiro;
    private javax.swing.JMenuItem pagamentoFinanceiro;
    private javax.swing.JMenuItem pecas;
    private javax.swing.JMenuItem pecasMenu;
    private javax.swing.JMenuItem relatorioFinanceiro;
    private javax.swing.JMenu servico;
    private javax.swing.JMenuItem transporteConsultas;
    private javax.swing.JMenuItem turista;
    private javax.swing.JMenuItem veiculosConsultas;
    private javax.swing.JMenuItem veiculosMenu;
    private javax.swing.JMenuItem viagensConsultas;
    private javax.swing.JMenuItem viagensServico;
    // End of variables declaration//GEN-END:variables
}
